#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ load("/lib/create_component.lib.yml", "single_build_component")
#@ load("/lib/util.lib.yml", "seq_join")

---
#@ def boost_libs():
- regex   #! used by: source-highlight
- test    #! used by: revng, revng-c
#@ end

#@yaml/text-templated-strings
---
#@ def boost():
license: LICENSE_1_0.txt
configure: |
  mkdir -p "$BUILD_DIR"

  extract.sh --into "$BUILD_DIR" "https://downloads.sourceforge.net/project/boost/boost/1.72.0/boost_1_72_0.tar.bz2"
  patch-if-exists "${ORCHESTRA_DOTDIR}/patches/boost-1.63.0-icl-disable-LessThanComparableConcept.patch" "$BUILD_DIR"
  cd "$BUILD_DIR"

  ./bootstrap.sh --prefix="$ORCHESTRA_ROOT" --with-libraries=(@= seq_join(boost_libs(), ",") @)
install: |
  cd "$BUILD_DIR"

  ./b2 \
    --prefix="${DESTDIR}${ORCHESTRA_ROOT}" \
    --ignore-site-config toolset='clang'

  ./b2 \
    --prefix="${DESTDIR}${ORCHESTRA_ROOT}" \
    --ignore-site-config toolset='clang' \
    install

build_dependencies:
  - host-cxx-toolchain
  - glibc
dependencies:
  - host-libcxx
  - libunwind
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  boost: #@ single_build_component(**boost())
