#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-src.tgz"

#@yaml/text-templated-strings
---
#@ def icu_args():
license: LICENSE
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)

  cd "$BUILD_DIR"
  ./source/configure \
    --disable-static \
    --disable-debug \
    --disable-samples \
    --disable-tests \
    --enable-shared \
    --enable-tools \
    --prefix="$ORCHESTRA_ROOT"
build_system: make
build_dependencies:
  - host-cxx-toolchain
  - glibc
  - python
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  icu: #@ single_build_component(**icu_args())
