#@ load("@ytt:overlay", "overlay")
#@ load("/lib/make.lib.yml", "make")

#@yaml/text-templated-strings
---
#@ def ninja_component():
#@    source_url = "https://github.com/ninja-build/ninja/archive/refs/tags/v1.11.0.tar.gz"
license: COPYING
builds:
  default:
    build_dependencies:
      - cmake
    configure: |
      mkdir -p "$BUILD_DIR/build"
      extract.sh --into "$BUILD_DIR" (@= source_url @)
      patch-if-exists "${ORCHESTRA_DOTDIR}/patches/ninja-shell-for-rule.patch" "$BUILD_DIR"
      cd "$BUILD_DIR/build"
      cmake \
        "$BUILD_DIR" \
        -Wno-dev \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=$ORCHESTRA_ROOT
    install: |
      cd "$BUILD_DIR/build"
      (@= make @)
      (@= make @) install
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  ninja: #@ ninja_component()
