#@ load("/lib/fn_args.lib.yml", "mandatory")
#@ load("@ytt:overlay", "overlay")

#@ architectures = ["arm", "x86-64", "i386", "s390x", "aarch64", "mips", "mipsel", "native"]

#@yaml/text-templated-strings
---
#@ def revng_test_component(options=mandatory):
builds:
  default:
    configure: |
      mkdir -p "$BUILD_DIR"
    install: |
      cd "$BUILD_DIR"
      rm -rf *
      revng \
        test-configure \
        "$ORCHESTRA_ROOT/share/revng/test/configuration"/**/*.yml \
        --install-path "$ORCHESTRA_ROOT/share/revng/test" \
        --destination . \
        (@= options["configure_args"] @)
      ninja run-all
      ninja install
    build_dependencies: #@ options["build_dependencies"]
#@ end

#@ def revng_qa_test():
configure_args: --target-type 'revng-qa\..*'
build_dependencies:
  - ninja
  - revng-qa
  - toolchain/win32-vc16/vc
  #@ for architecture in architectures:
  - toolchain/(@= architecture if architecture != "native" else "host" @)/gcc
  #@ end
#@ end

#@ def revng_test():
configure_args: --target-type 'revng\..*'
build_dependencies:
  - ninja
  - revng
  - revng-qa
  - test/revng-qa
#@ end

#@ def revng_c_test():
configure_args: --target-type 'revng-c\..*'
build_dependencies:
  - ninja
  - revng-c
  - revng-qa
  - test/revng
  - test/revng-qa
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
#@yaml/text-templated-strings
components:
  test/revng-qa: #@ revng_test_component(revng_qa_test())
  test/revng: #@ revng_test_component(revng_test())
  test/revng-c: #@ revng_test_component(revng_c_test())
